import mongoose from 'mongoose'
import dotenv from 'dotenv'

// Explicitly point it to the Next.js local environment file
dotenv.config({ path: '.env.local' })
// 1. Recreate the basic schema shape for the script
const profileSchema = new mongoose.Schema(
  {
    firstName: String,
    lastName: String,
    gender: String,
    age: Number,
    height: String,
    city: String,
    country: String,
    designation: String,
    currentCompany: String,
    income: Number,
    degree: String,
    undergraduateCollege: String,
    religion: String,
    caste: String,
    diet: String,
    wantKids: String,
    openToRelocate: String,
    openToPets: String,
    languagesKnown: [String],
    maritalStatus: String,
    email: String,
    phoneNumber: String,
    imageUrl: String,
  },
  { strict: false },
) // strict: false allows any extra fields to pass through safely

// Register the model (or grab it if it already exists)
const Profile =
  mongoose.models.Profile || mongoose.model('Profile', profileSchema)

async function seedDatabase() {
  try {
    console.log('⏳ Connecting to MongoDB...')
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('✅ Connected to Database!')

    // 2. THE NUKE COMMAND: This completely empties the collection
    console.log('🗑️ Deleting old data...')
    await Profile.deleteMany({})
    console.log('✅ Old data deleted!')

    // 3. YOUR FRESH DATA: This is where you will eventually paste your 100 profiles
    const freshData = [
      {
        id: '1',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Sandeep',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1992-10-14',
        age: 34,
        country: 'India',
        city: 'Jaipur',
        height: `6'3"`,
        email: 'sandeep.sharma1@example.com',
        phoneNumber: '+91-7023020667',
        undergraduateCollege: 'Manipal University',
        degree: 'MBBS',
        income: 2288558,
        currentCompany: 'Accenture',
        designation: 'Architect',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 1,
        caste: 'Jain',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '2',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Pooja',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '1996-07-21',
        age: 30,
        country: 'India',
        city: 'Chennai',
        height: `6'6"`,
        email: 'pooja.agarwal2@example.com',
        phoneNumber: '+91-7731293861',
        undergraduateCollege: 'BITS Pilani',
        degree: 'B.Tech IT',
        income: 1096584,
        currentCompany: 'Wipro',
        designation: 'Senior Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 2,
        caste: 'Jain',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '3',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Arjun',
        lastName: 'Yadav',
        gender: 'Male',
        dateOfBirth: '2001-02-06',
        age: 25,
        country: 'India',
        city: 'Hyderabad',
        height: `6'2"`,
        email: 'arjun.yadav3@example.com',
        phoneNumber: '+91-9968329061',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'BBA',
        income: 918537,
        currentCompany: 'Cognizant',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 2,
        caste: 'Yadav',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '4',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Priya',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '1992-06-20',
        age: 34,
        country: 'India',
        city: 'Mumbai',
        height: `5'8"`,
        email: 'priya.gupta4@example.com',
        phoneNumber: '+91-9802371150',
        undergraduateCollege: 'NIT Trichy',
        degree: 'M.Tech',
        income: 3344439,
        currentCompany: 'TCS',
        designation: 'Software Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 3,
        caste: 'Brahmin',
        religion: 'Hindu',
        diet: 'Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '5',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Amit',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '1991-11-21',
        age: 35,
        country: 'India',
        city: 'Hyderabad',
        height: `6'1"`,
        email: 'amit.verma5@example.com',
        phoneNumber: '+91-8134567161',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Tech IT',
        income: 1194143,
        currentCompany: 'Tech Mahindra',
        designation: 'Developer',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Telugu'],
        siblings: 1,
        caste: 'Yadav',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '6',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Sneha',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '1996-09-01',
        age: 30,
        country: 'India',
        city: 'Mumbai',
        height: `6'1"`,
        email: 'sneha.gupta6@example.com',
        phoneNumber: '+91-7366841572',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Tech ECE',
        income: 1502386,
        currentCompany: 'Cognizant',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 1,
        caste: 'Kayastha',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '7',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Amit',
        lastName: 'Jain',
        gender: 'Male',
        dateOfBirth: '1991-10-10',
        age: 35,
        country: 'India',
        city: 'Pune',
        height: `6'2"`,
        email: 'amit.jain7@example.com',
        phoneNumber: '+91-9186730176',
        undergraduateCollege: 'IIM Indore',
        degree: 'MCA',
        income: 1239414,
        currentCompany: 'Cognizant',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Telugu'],
        siblings: 0,
        caste: 'Maratha',
        religion: 'Hindu',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '8',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Pooja',
        lastName: 'Patel',
        gender: 'Female',
        dateOfBirth: '1996-11-25',
        age: 30,
        country: 'India',
        city: 'Jaipur',
        height: `5'5"`,
        email: 'pooja.patel8@example.com',
        phoneNumber: '+91-9117489842',
        undergraduateCollege: 'BITS Pilani',
        degree: 'B.Com',
        income: 2254971,
        currentCompany: 'Microsoft',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 1,
        caste: 'Reddy',
        religion: 'Hindu',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '9',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Amit',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '2000-02-25',
        age: 26,
        country: 'India',
        city: 'Delhi',
        height: `6'1"`,
        email: 'amit.mishra9@example.com',
        phoneNumber: '+91-7277452941',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Tech Computer Science',
        income: 1677679,
        currentCompany: 'Google',
        designation: 'Designer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Rajput',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '10',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Neha',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '1994-05-24',
        age: 32,
        country: 'India',
        city: 'Pune',
        height: `5'7"`,
        email: 'neha.gupta10@example.com',
        phoneNumber: '+91-9633299163',
        undergraduateCollege: 'IIM Indore',
        degree: 'MBA',
        income: 4104590,
        currentCompany: 'HCL',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 2,
        caste: 'Brahmin',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '11',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Nitin',
        lastName: 'Joshi',
        gender: 'Male',
        dateOfBirth: '1995-03-05',
        age: 31,
        country: 'India',
        city: 'Kolkata',
        height: `7'2"`,
        email: 'nitin.joshi11@example.com',
        phoneNumber: '+91-8504513623',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Des Fashion Design',
        income: 540928,
        currentCompany: 'HCL',
        designation: 'Analyst',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 3,
        caste: 'Jain',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '12',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Sneha',
        lastName: 'Patel',
        gender: 'Female',
        dateOfBirth: '1999-06-15',
        age: 27,
        country: 'India',
        city: 'Kolkata',
        height: `6'6"`,
        email: 'sneha.patel12@example.com',
        phoneNumber: '+91-9922029534',
        undergraduateCollege: 'IIT Delhi',
        degree: 'M.Tech',
        income: 4282892,
        currentCompany: 'Amazon',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Kayastha',
        religion: 'Muslim',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '13',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Karan',
        lastName: 'Jain',
        gender: 'Male',
        dateOfBirth: '1993-04-20',
        age: 33,
        country: 'India',
        city: 'Chennai',
        height: `6'0"`,
        email: 'karan.jain13@example.com',
        phoneNumber: '+91-7147294588',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Tech ECE',
        income: 1558870,
        currentCompany: 'TCS',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 2,
        caste: 'Kshatriya',
        religion: 'Jain',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '14',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Anjali',
        lastName: 'Sharma',
        gender: 'Female',
        dateOfBirth: '2001-11-05',
        age: 25,
        country: 'India',
        city: 'Ahmedabad',
        height: `5'2"`,
        email: 'anjali.sharma14@example.com',
        phoneNumber: '+91-9425837351',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Tech IT',
        income: 1832497,
        currentCompany: 'TCS',
        designation: 'Developer',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 3,
        caste: 'Brahmin',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '15',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Amit',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '1994-03-14',
        age: 32,
        country: 'India',
        city: 'Pune',
        height: `6'6"`,
        email: 'amit.verma15@example.com',
        phoneNumber: '+91-8408407440',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Des Fashion Design',
        income: 1192124,
        currentCompany: 'Tech Mahindra',
        designation: 'Analyst',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Agarwal',
        religion: 'Jain',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '16',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Anjali',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '2001-05-08',
        age: 25,
        country: 'India',
        city: 'Hyderabad',
        height: `6'0"`,
        email: 'anjali.agarwal16@example.com',
        phoneNumber: '+91-7682565123',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Des Fashion Design',
        income: 4076382,
        currentCompany: 'Wipro',
        designation: 'Analyst',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Reddy',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '17',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Amit',
        lastName: 'Gupta',
        gender: 'Male',
        dateOfBirth: '1998-08-13',
        age: 28,
        country: 'India',
        city: 'Bangalore',
        height: `7'3"`,
        email: 'amit.gupta17@example.com',
        phoneNumber: '+91-8438845405',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Tech Computer Science',
        income: 1291810,
        currentCompany: 'Cognizant',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Telugu'],
        siblings: 0,
        caste: 'Kayastha',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '18',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Sneha',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '1994-05-22',
        age: 32,
        country: 'India',
        city: 'Indore',
        height: `6'3"`,
        email: 'sneha.singh18@example.com',
        phoneNumber: '+91-7178086292',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Tech Computer Science',
        income: 1281846,
        currentCompany: 'Cognizant',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Reddy',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '19',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Karan',
        lastName: 'Joshi',
        gender: 'Male',
        dateOfBirth: '2002-12-21',
        age: 24,
        country: 'India',
        city: 'Indore',
        height: `7'1"`,
        email: 'karan.joshi19@example.com',
        phoneNumber: '+91-7270732335',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Com',
        income: 935353,
        currentCompany: 'Tech Mahindra',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 2,
        caste: 'Jain',
        religion: 'Hindu',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '20',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Anjali',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '2000-07-05',
        age: 26,
        country: 'India',
        city: 'Hyderabad',
        height: `6'2"`,
        email: 'anjali.gupta20@example.com',
        phoneNumber: '+91-9780380151',
        undergraduateCollege: 'NIFT',
        degree: 'MCA',
        income: 3690857,
        currentCompany: 'Amazon',
        designation: 'Consultant',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Telugu'],
        siblings: 2,
        caste: 'Kshatriya',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '21',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Amit',
        lastName: 'Patel',
        gender: 'Male',
        dateOfBirth: '1992-05-08',
        age: 34,
        country: 'India',
        city: 'Kolkata',
        height: `6'8"`,
        email: 'amit.patel21@example.com',
        phoneNumber: '+91-8507943843',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Des Fashion Design',
        income: 2735971,
        currentCompany: 'Amazon',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Yadav',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '22',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Nidhi',
        lastName: 'Jain',
        gender: 'Female',
        dateOfBirth: '1998-05-19',
        age: 28,
        country: 'India',
        city: 'Ahmedabad',
        height: `5'4"`,
        email: 'nidhi.jain22@example.com',
        phoneNumber: '+91-9612834916',
        undergraduateCollege: 'NIFT',
        degree: 'MCA',
        income: 4396256,
        currentCompany: 'Google',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Jain',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '23',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Amit',
        lastName: 'Agarwal',
        gender: 'Male',
        dateOfBirth: '1991-08-08',
        age: 35,
        country: 'India',
        city: 'Kolkata',
        height: `6'4"`,
        email: 'amit.agarwal23@example.com',
        phoneNumber: '+91-7553157292',
        undergraduateCollege: 'VIT Vellore',
        degree: 'MCA',
        income: 1855293,
        currentCompany: 'Wipro',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Brahmin',
        religion: 'Sikh',
        diet: 'Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '24',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Nidhi',
        lastName: 'Sharma',
        gender: 'Female',
        dateOfBirth: '2000-05-04',
        age: 26,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'2"`,
        email: 'nidhi.sharma24@example.com',
        phoneNumber: '+91-8172951960',
        undergraduateCollege: 'NIFT',
        degree: 'B.Des Fashion Design',
        income: 4675822,
        currentCompany: 'Wipro',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Rajput',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '25',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Rohit',
        lastName: 'Joshi',
        gender: 'Male',
        dateOfBirth: '2001-05-08',
        age: 25,
        country: 'India',
        city: 'Hyderabad',
        height: `6'9"`,
        email: 'rohit.joshi25@example.com',
        phoneNumber: '+91-8016866232',
        undergraduateCollege: 'Delhi University',
        degree: 'M.Tech',
        income: 689231,
        currentCompany: 'Amazon',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Telugu'],
        siblings: 3,
        caste: 'Rajput',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '26',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Neha',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '2000-01-26',
        age: 26,
        country: 'India',
        city: 'Mumbai',
        height: `5'3"`,
        email: 'neha.agarwal26@example.com',
        phoneNumber: '+91-8283651170',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Des Fashion Design',
        income: 1099585,
        currentCompany: 'Cognizant',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 0,
        caste: 'Patidar',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '27',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Vikram',
        lastName: 'Agarwal',
        gender: 'Male',
        dateOfBirth: '1996-08-24',
        age: 30,
        country: 'India',
        city: 'Delhi',
        height: `6'7"`,
        email: 'vikram.agarwal27@example.com',
        phoneNumber: '+91-8947044960',
        undergraduateCollege: 'Manipal University',
        degree: 'MBBS',
        income: 4224143,
        currentCompany: 'Cognizant',
        designation: 'Senior Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Rajput',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '28',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Kavya',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1999-11-18',
        age: 27,
        country: 'India',
        city: 'Hyderabad',
        height: `6'6"`,
        email: 'kavya.mishra28@example.com',
        phoneNumber: '+91-8693973705',
        undergraduateCollege: 'VIT Vellore',
        degree: 'M.Tech',
        income: 2841232,
        currentCompany: 'Accenture',
        designation: 'Software Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 1,
        caste: 'Rajput',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '29',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Nitin',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1996-07-14',
        age: 30,
        country: 'India',
        city: 'Jaipur',
        height: `7'0"`,
        email: 'nitin.mishra29@example.com',
        phoneNumber: '+91-7897218370',
        undergraduateCollege: 'Delhi University',
        degree: 'MBA',
        income: 1855319,
        currentCompany: 'HCL',
        designation: 'Software Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Agarwal',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '30',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Sneha',
        lastName: 'Jain',
        gender: 'Female',
        dateOfBirth: '2001-02-09',
        age: 25,
        country: 'India',
        city: 'Chennai',
        height: `5'6"`,
        email: 'sneha.jain30@example.com',
        phoneNumber: '+91-9373163223',
        undergraduateCollege: 'IIM Indore',
        degree: 'B.Tech IT',
        income: 1600544,
        currentCompany: 'TCS',
        designation: 'Product Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 3,
        caste: 'Rajput',
        religion: 'Sikh',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '31',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Amit',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1998-07-12',
        age: 28,
        country: 'India',
        city: 'Jaipur',
        height: `7'2"`,
        email: 'amit.sharma31@example.com',
        phoneNumber: '+91-8369896879',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'MBA',
        income: 2299469,
        currentCompany: 'Wipro',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 3,
        caste: 'Maratha',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '32',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Neha',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '1992-11-26',
        age: 34,
        country: 'India',
        city: 'Bangalore',
        height: `6'0"`,
        email: 'neha.agarwal32@example.com',
        phoneNumber: '+91-9159862320',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Com',
        income: 1285693,
        currentCompany: 'Amazon',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Reddy',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '33',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Amit',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1995-06-25',
        age: 31,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'6"`,
        email: 'amit.sharma33@example.com',
        phoneNumber: '+91-9342619184',
        undergraduateCollege: 'NIFT',
        degree: 'M.Tech',
        income: 917231,
        currentCompany: 'TCS',
        designation: 'Designer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Jain',
        religion: 'Jain',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '34',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Sneha',
        lastName: 'Sharma',
        gender: 'Female',
        dateOfBirth: '2000-09-15',
        age: 26,
        country: 'India',
        city: 'Delhi',
        height: `5'2"`,
        email: 'sneha.sharma34@example.com',
        phoneNumber: '+91-8734862147',
        undergraduateCollege: 'IIT Delhi',
        degree: 'MBA',
        income: 3682083,
        currentCompany: 'Amazon',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 3,
        caste: 'Kshatriya',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '35',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Ankit',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1997-04-02',
        age: 29,
        country: 'India',
        city: 'Jaipur',
        height: `6'2"`,
        email: 'ankit.mishra35@example.com',
        phoneNumber: '+91-7647492902',
        undergraduateCollege: 'NIFT',
        degree: 'BBA',
        income: 4279230,
        currentCompany: 'HCL',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 0,
        caste: 'Brahmin',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '36',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Shreya',
        lastName: 'Jain',
        gender: 'Female',
        dateOfBirth: '1991-05-16',
        age: 35,
        country: 'India',
        city: 'Mumbai',
        height: `5'3"`,
        email: 'shreya.jain36@example.com',
        phoneNumber: '+91-9841748493',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Tech Computer Science',
        income: 804721,
        currentCompany: 'Wipro',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 1,
        caste: 'Maratha',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '37',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Arjun',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1995-02-15',
        age: 31,
        country: 'India',
        city: 'Jaipur',
        height: `6'0"`,
        email: 'arjun.sharma37@example.com',
        phoneNumber: '+91-7354561924',
        undergraduateCollege: 'IIT Bombay',
        degree: 'MBBS',
        income: 4486612,
        currentCompany: 'Microsoft',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Brahmin',
        religion: 'Muslim',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '38',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Shreya',
        lastName: 'Patel',
        gender: 'Female',
        dateOfBirth: '1991-07-04',
        age: 35,
        country: 'India',
        city: 'Pune',
        height: `6'6"`,
        email: 'shreya.patel38@example.com',
        phoneNumber: '+91-9107664113',
        undergraduateCollege: 'NIFT',
        degree: 'B.Tech IT',
        income: 1971346,
        currentCompany: 'Accenture',
        designation: 'Architect',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 0,
        caste: 'Jain',
        religion: 'Muslim',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '39',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Manish',
        lastName: 'Patel',
        gender: 'Male',
        dateOfBirth: '1995-05-10',
        age: 31,
        country: 'India',
        city: 'Delhi',
        height: `6'6"`,
        email: 'manish.patel39@example.com',
        phoneNumber: '+91-7574848703',
        undergraduateCollege: 'NIFT',
        degree: 'B.Tech Computer Science',
        income: 1208245,
        currentCompany: 'Accenture',
        designation: 'Developer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 3,
        caste: 'Yadav',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '40',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Pooja',
        lastName: 'Sharma',
        gender: 'Female',
        dateOfBirth: '1997-07-04',
        age: 29,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'2"`,
        email: 'pooja.sharma40@example.com',
        phoneNumber: '+91-7705606657',
        undergraduateCollege: 'VIT Vellore',
        degree: 'MBBS',
        income: 2381092,
        currentCompany: 'Accenture',
        designation: 'Consultant',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 0,
        caste: 'Agarwal',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '41',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Nitin',
        lastName: 'Patel',
        gender: 'Male',
        dateOfBirth: '1996-12-11',
        age: 30,
        country: 'India',
        city: 'Jaipur',
        height: `6'1"`,
        email: 'nitin.patel41@example.com',
        phoneNumber: '+91-9154199887',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Des Fashion Design',
        income: 3224167,
        currentCompany: 'Cognizant',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Patidar',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '42',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Nidhi',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1992-07-18',
        age: 34,
        country: 'India',
        city: 'Mumbai',
        height: `6'1"`,
        email: 'nidhi.mishra42@example.com',
        phoneNumber: '+91-8872369831',
        undergraduateCollege: 'Manipal University',
        degree: 'BBA',
        income: 3591533,
        currentCompany: 'Wipro',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 1,
        caste: 'Kshatriya',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '43',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Karan',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '1993-06-04',
        age: 33,
        country: 'India',
        city: 'Kolkata',
        height: `6'2"`,
        email: 'karan.verma43@example.com',
        phoneNumber: '+91-8697496115',
        undergraduateCollege: 'NIFT',
        degree: 'MCA',
        income: 4081379,
        currentCompany: 'Accenture',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 1,
        caste: 'Jain',
        religion: 'Muslim',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '44',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Anjali',
        lastName: 'Verma',
        gender: 'Female',
        dateOfBirth: '1997-11-25',
        age: 29,
        country: 'India',
        city: 'Mumbai',
        height: `5'3"`,
        email: 'anjali.verma44@example.com',
        phoneNumber: '+91-8281882151',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Des Fashion Design',
        income: 3564876,
        currentCompany: 'Cognizant',
        designation: 'Consultant',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Reddy',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '45',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Rahul',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1993-09-28',
        age: 33,
        country: 'India',
        city: 'Delhi',
        height: `7'2"`,
        email: 'rahul.mishra45@example.com',
        phoneNumber: '+91-9801231482',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Des Fashion Design',
        income: 3688152,
        currentCompany: 'Google',
        designation: 'Analyst',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Rajput',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '46',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Aarti',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '1998-01-10',
        age: 28,
        country: 'India',
        city: 'Ahmedabad',
        height: `5'3"`,
        email: 'aarti.agarwal46@example.com',
        phoneNumber: '+91-9423392568',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Des Fashion Design',
        income: 2834932,
        currentCompany: 'Microsoft',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Telugu'],
        siblings: 2,
        caste: 'Agarwal',
        religion: 'Hindu',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '47',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Manish',
        lastName: 'Yadav',
        gender: 'Male',
        dateOfBirth: '2002-05-26',
        age: 24,
        country: 'India',
        city: 'Bangalore',
        height: `6'7"`,
        email: 'manish.yadav47@example.com',
        phoneNumber: '+91-8918123734',
        undergraduateCollege: 'IIT Delhi',
        degree: 'M.Tech',
        income: 4241875,
        currentCompany: 'Wipro',
        designation: 'Analyst',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 0,
        caste: 'Kshatriya',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '48',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Neha',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '1999-11-13',
        age: 27,
        country: 'India',
        city: 'Pune',
        height: `6'5"`,
        email: 'neha.singh48@example.com',
        phoneNumber: '+91-9115681715',
        undergraduateCollege: 'IIT Delhi',
        degree: 'MBA',
        income: 2087289,
        currentCompany: 'Infosys',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Kshatriya',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '49',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Sandeep',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1997-09-17',
        age: 29,
        country: 'India',
        city: 'Pune',
        height: `6'7"`,
        email: 'sandeep.sharma49@example.com',
        phoneNumber: '+91-9695276440',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Tech IT',
        income: 3449874,
        currentCompany: 'HCL',
        designation: 'Senior Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Telugu'],
        siblings: 1,
        caste: 'Patidar',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '50',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Priya',
        lastName: 'Verma',
        gender: 'Female',
        dateOfBirth: '1994-03-01',
        age: 32,
        country: 'India',
        city: 'Kolkata',
        height: `6'2"`,
        email: 'priya.verma50@example.com',
        phoneNumber: '+91-7509872404',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Des Fashion Design',
        income: 4449739,
        currentCompany: 'Cognizant',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 3,
        caste: 'Kshatriya',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '51',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Amit',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1996-12-26',
        age: 30,
        country: 'India',
        city: 'Jaipur',
        height: `6'4"`,
        email: 'amit.sharma51@example.com',
        phoneNumber: '+91-8007802110',
        undergraduateCollege: 'IIM Indore',
        degree: 'MBBS',
        income: 4078066,
        currentCompany: 'Cognizant',
        designation: 'Analyst',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 0,
        caste: 'Maratha',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '52',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Sneha',
        lastName: 'Joshi',
        gender: 'Female',
        dateOfBirth: '1993-08-27',
        age: 33,
        country: 'India',
        city: 'Indore',
        height: `6'2"`,
        email: 'sneha.joshi52@example.com',
        phoneNumber: '+91-8839684520',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Des Fashion Design',
        income: 4694580,
        currentCompany: 'Cognizant',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 1,
        caste: 'Yadav',
        religion: 'Muslim',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '53',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Amit',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1995-03-19',
        age: 31,
        country: 'India',
        city: 'Delhi',
        height: `6'8"`,
        email: 'amit.mishra53@example.com',
        phoneNumber: '+91-9825269368',
        undergraduateCollege: 'BITS Pilani',
        degree: 'B.Des Fashion Design',
        income: 1718721,
        currentCompany: 'Google',
        designation: 'Developer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 2,
        caste: 'Patidar',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '54',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Anjali',
        lastName: 'Yadav',
        gender: 'Female',
        dateOfBirth: '2002-10-18',
        age: 24,
        country: 'India',
        city: 'Kolkata',
        height: `5'4"`,
        email: 'anjali.yadav54@example.com',
        phoneNumber: '+91-9425105507',
        undergraduateCollege: 'IIT Bombay',
        degree: 'MBA',
        income: 878420,
        currentCompany: 'Google',
        designation: 'Consultant',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Sikh',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '55',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Arjun',
        lastName: 'Gupta',
        gender: 'Male',
        dateOfBirth: '2001-12-22',
        age: 25,
        country: 'India',
        city: 'Indore',
        height: `6'6"`,
        email: 'arjun.gupta55@example.com',
        phoneNumber: '+91-9888912189',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Com',
        income: 3936271,
        currentCompany: 'Microsoft',
        designation: 'Analyst',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 2,
        caste: 'Patidar',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '56',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Pooja',
        lastName: 'Yadav',
        gender: 'Female',
        dateOfBirth: '2002-01-01',
        age: 24,
        country: 'India',
        city: 'Kolkata',
        height: `5'9"`,
        email: 'pooja.yadav56@example.com',
        phoneNumber: '+91-7029631993',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Tech IT',
        income: 4376044,
        currentCompany: 'Infosys',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 1,
        caste: 'Kshatriya',
        religion: 'Muslim',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '57',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Amit',
        lastName: 'Agarwal',
        gender: 'Male',
        dateOfBirth: '1991-04-12',
        age: 35,
        country: 'India',
        city: 'Bangalore',
        height: `7'2"`,
        email: 'amit.agarwal57@example.com',
        phoneNumber: '+91-8235261220',
        undergraduateCollege: 'BITS Pilani',
        degree: 'B.Com',
        income: 2771335,
        currentCompany: 'HCL',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 1,
        caste: 'Yadav',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '58',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Shreya',
        lastName: 'Jain',
        gender: 'Female',
        dateOfBirth: '1995-08-05',
        age: 31,
        country: 'India',
        city: 'Indore',
        height: `5'2"`,
        email: 'shreya.jain58@example.com',
        phoneNumber: '+91-9492406194',
        undergraduateCollege: 'Delhi University',
        degree: 'MCA',
        income: 2121372,
        currentCompany: 'Wipro',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Patidar',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '59',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Manish',
        lastName: 'Yadav',
        gender: 'Male',
        dateOfBirth: '2002-07-03',
        age: 24,
        country: 'India',
        city: 'Hyderabad',
        height: `6'0"`,
        email: 'manish.yadav59@example.com',
        phoneNumber: '+91-7064332423',
        undergraduateCollege: 'NIFT',
        degree: 'MBA',
        income: 758279,
        currentCompany: 'TCS',
        designation: 'Architect',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 0,
        caste: 'Patidar',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '60',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Neha',
        lastName: 'Joshi',
        gender: 'Female',
        dateOfBirth: '2000-01-01',
        age: 26,
        country: 'India',
        city: 'Indore',
        height: `5'5"`,
        email: 'neha.joshi60@example.com',
        phoneNumber: '+91-9224063315',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Tech Computer Science',
        income: 2434725,
        currentCompany: 'Wipro',
        designation: 'Consultant',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Telugu'],
        siblings: 3,
        caste: 'Reddy',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '61',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Rahul',
        lastName: 'Singh',
        gender: 'Male',
        dateOfBirth: '1996-03-13',
        age: 30,
        country: 'India',
        city: 'Indore',
        height: `6'7"`,
        email: 'rahul.singh61@example.com',
        phoneNumber: '+91-7250826488',
        undergraduateCollege: 'IIM Indore',
        degree: 'MCA',
        income: 1422331,
        currentCompany: 'Infosys',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Yadav',
        religion: 'Muslim',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '62',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Riya',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1991-08-01',
        age: 35,
        country: 'India',
        city: 'Jaipur',
        height: `5'6"`,
        email: 'riya.mishra62@example.com',
        phoneNumber: '+91-7214504176',
        undergraduateCollege: 'NIFT',
        degree: 'MBBS',
        income: 3324325,
        currentCompany: 'Cognizant',
        designation: 'Developer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Maratha',
        religion: 'Hindu',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '63',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Nitin',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '2000-02-04',
        age: 26,
        country: 'India',
        city: 'Pune',
        height: `7'3"`,
        email: 'nitin.sharma63@example.com',
        phoneNumber: '+91-7736317071',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Tech ECE',
        income: 1247077,
        currentCompany: 'Microsoft',
        designation: 'Consultant',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Maratha',
        religion: 'Hindu',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '64',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Nidhi',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '2002-01-08',
        age: 24,
        country: 'India',
        city: 'Pune',
        height: `5'9"`,
        email: 'nidhi.agarwal64@example.com',
        phoneNumber: '+91-7080845958',
        undergraduateCollege: 'VIT Vellore',
        degree: 'B.Tech IT',
        income: 862624,
        currentCompany: 'Tech Mahindra',
        designation: 'Doctor',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Hindu',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '65',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Rahul',
        lastName: 'Singh',
        gender: 'Male',
        dateOfBirth: '1992-10-20',
        age: 34,
        country: 'India',
        city: 'Jaipur',
        height: `7'0"`,
        email: 'rahul.singh65@example.com',
        phoneNumber: '+91-9928005841',
        undergraduateCollege: 'IIM Indore',
        degree: 'B.Tech ECE',
        income: 2771158,
        currentCompany: 'Microsoft',
        designation: 'Software Engineer',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Maratha',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '66',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Anjali',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '2002-06-06',
        age: 24,
        country: 'India',
        city: 'Chennai',
        height: `6'3"`,
        email: 'anjali.singh66@example.com',
        phoneNumber: '+91-9348784760',
        undergraduateCollege: 'NIFT',
        degree: 'MCA',
        income: 4617949,
        currentCompany: 'Wipro',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '67',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Ankit',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1998-09-15',
        age: 28,
        country: 'India',
        city: 'Pune',
        height: `6'5"`,
        email: 'ankit.sharma67@example.com',
        phoneNumber: '+91-9079844757',
        undergraduateCollege: 'Manipal University',
        degree: 'MCA',
        income: 871380,
        currentCompany: 'Wipro',
        designation: 'Doctor',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Reddy',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '68',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Priya',
        lastName: 'Joshi',
        gender: 'Female',
        dateOfBirth: '1996-08-09',
        age: 30,
        country: 'India',
        city: 'Bangalore',
        height: `6'6"`,
        email: 'priya.joshi68@example.com',
        phoneNumber: '+91-7372961065',
        undergraduateCollege: 'IIT Bombay',
        degree: 'MBBS',
        income: 2594627,
        currentCompany: 'Microsoft',
        designation: 'Senior Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Telugu'],
        siblings: 1,
        caste: 'Yadav',
        religion: 'Muslim',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '69',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Arjun',
        lastName: 'Jain',
        gender: 'Male',
        dateOfBirth: '2002-12-22',
        age: 24,
        country: 'India',
        city: 'Delhi',
        height: `6'4"`,
        email: 'arjun.jain69@example.com',
        phoneNumber: '+91-9283230656',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Tech Computer Science',
        income: 996753,
        currentCompany: 'Wipro',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Kshatriya',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '70',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Sneha',
        lastName: 'Patel',
        gender: 'Female',
        dateOfBirth: '1997-11-20',
        age: 29,
        country: 'India',
        city: 'Ahmedabad',
        height: `5'9"`,
        email: 'sneha.patel70@example.com',
        phoneNumber: '+91-9284450155',
        undergraduateCollege: 'IIT Bombay',
        degree: 'M.Tech',
        income: 2908925,
        currentCompany: 'Infosys',
        designation: 'Developer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 0,
        caste: 'Maratha',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'Maybe',
        openToPets: 'Yes',
        status: 'Reviewing',
      },
      {
        id: '71',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Amit',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '1992-06-20',
        age: 34,
        country: 'India',
        city: 'Kolkata',
        height: `6'3"`,
        email: 'amit.verma71@example.com',
        phoneNumber: '+91-9200375432',
        undergraduateCollege: 'Manipal University',
        degree: 'MBBS',
        income: 1687971,
        currentCompany: 'Cognizant',
        designation: 'Analyst',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '72',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Riya',
        lastName: 'Agarwal',
        gender: 'Female',
        dateOfBirth: '2000-02-25',
        age: 26,
        country: 'India',
        city: 'Chennai',
        height: `6'4"`,
        email: 'riya.agarwal72@example.com',
        phoneNumber: '+91-7357068987',
        undergraduateCollege: 'Manipal University',
        degree: 'B.Com',
        income: 2979613,
        currentCompany: 'Microsoft',
        designation: 'Analyst',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 3,
        caste: 'Jain',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '73',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Manish',
        lastName: 'Joshi',
        gender: 'Male',
        dateOfBirth: '2002-08-13',
        age: 24,
        country: 'India',
        city: 'Kolkata',
        height: `6'0"`,
        email: 'manish.joshi73@example.com',
        phoneNumber: '+91-8525130993',
        undergraduateCollege: 'IIT Delhi',
        degree: 'BBA',
        income: 4045801,
        currentCompany: 'Wipro',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 3,
        caste: 'Yadav',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '74',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Anjali',
        lastName: 'Sharma',
        gender: 'Female',
        dateOfBirth: '1994-08-03',
        age: 32,
        country: 'India',
        city: 'Chennai',
        height: `5'8"`,
        email: 'anjali.sharma74@example.com',
        phoneNumber: '+91-8164992260',
        undergraduateCollege: 'NIFT',
        degree: 'MBBS',
        income: 3437620,
        currentCompany: 'Infosys',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Brahmin',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '75',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Karan',
        lastName: 'Patel',
        gender: 'Male',
        dateOfBirth: '1999-04-27',
        age: 27,
        country: 'India',
        city: 'Bangalore',
        height: `6'5"`,
        email: 'karan.patel75@example.com',
        phoneNumber: '+91-9838898714',
        undergraduateCollege: 'IIT Delhi',
        degree: 'M.Tech',
        income: 2602106,
        currentCompany: 'Infosys',
        designation: 'Architect',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 2,
        caste: 'Jain',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '76',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Anjali',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '2001-04-16',
        age: 25,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'3"`,
        email: 'anjali.gupta76@example.com',
        phoneNumber: '+91-9392613360',
        undergraduateCollege: 'VIT Vellore',
        degree: 'B.Com',
        income: 3657127,
        currentCompany: 'Wipro',
        designation: 'Developer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Kayastha',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '77',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Amit',
        lastName: 'Agarwal',
        gender: 'Male',
        dateOfBirth: '2002-02-16',
        age: 24,
        country: 'India',
        city: 'Indore',
        height: `7'2"`,
        email: 'amit.agarwal77@example.com',
        phoneNumber: '+91-9391742710',
        undergraduateCollege: 'BITS Pilani',
        degree: 'BBA',
        income: 1533341,
        currentCompany: 'Tech Mahindra',
        designation: 'Designer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Maratha',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '78',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Nidhi',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1993-08-16',
        age: 33,
        country: 'India',
        city: 'Hyderabad',
        height: `6'0"`,
        email: 'nidhi.mishra78@example.com',
        phoneNumber: '+91-8493400756',
        undergraduateCollege: 'NIFT',
        degree: 'MBBS',
        income: 2107487,
        currentCompany: 'Microsoft',
        designation: 'Consultant',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Maratha',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '79',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Rahul',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '2001-01-16',
        age: 25,
        country: 'India',
        city: 'Ahmedabad',
        height: `7'0"`,
        email: 'rahul.mishra79@example.com',
        phoneNumber: '+91-7044401129',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Tech ECE',
        income: 4220468,
        currentCompany: 'Wipro',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Yadav',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '80',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Anjali',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1994-11-08',
        age: 32,
        country: 'India',
        city: 'Mumbai',
        height: `5'8"`,
        email: 'anjali.mishra80@example.com',
        phoneNumber: '+91-9100086937',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Com',
        income: 1403948,
        currentCompany: 'Microsoft',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Kshatriya',
        religion: 'Sikh',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '81',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Manish',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '2002-01-18',
        age: 24,
        country: 'India',
        city: 'Delhi',
        height: `6'2"`,
        email: 'manish.verma81@example.com',
        phoneNumber: '+91-8152652841',
        undergraduateCollege: 'NIFT',
        degree: 'B.Tech ECE',
        income: 4420417,
        currentCompany: 'Amazon',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 0,
        caste: 'Rajput',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '82',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Nidhi',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '1993-01-22',
        age: 33,
        country: 'India',
        city: 'Indore',
        height: `6'2"`,
        email: 'nidhi.singh82@example.com',
        phoneNumber: '+91-8450116125',
        undergraduateCollege: 'NIFT',
        degree: 'B.Tech IT',
        income: 1243939,
        currentCompany: 'Accenture',
        designation: 'Consultant',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '83',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Nitin',
        lastName: 'Patel',
        gender: 'Male',
        dateOfBirth: '1994-07-10',
        age: 32,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'4"`,
        email: 'nitin.patel83@example.com',
        phoneNumber: '+91-9936981534',
        undergraduateCollege: 'IIM Indore',
        degree: 'MBBS',
        income: 3091264,
        currentCompany: 'Microsoft',
        designation: 'Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 3,
        caste: 'Rajput',
        religion: 'Muslim',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '84',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Sneha',
        lastName: 'Yadav',
        gender: 'Female',
        dateOfBirth: '2001-11-06',
        age: 25,
        country: 'India',
        city: 'Jaipur',
        height: `6'2"`,
        email: 'sneha.yadav84@example.com',
        phoneNumber: '+91-8401266874',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Tech Computer Science',
        income: 3907568,
        currentCompany: 'Amazon',
        designation: 'Product Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Rajput',
        religion: 'Sikh',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '85',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Karan',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1991-11-07',
        age: 35,
        country: 'India',
        city: 'Mumbai',
        height: `6'5"`,
        email: 'karan.sharma85@example.com',
        phoneNumber: '+91-8696608119',
        undergraduateCollege: 'NIT Trichy',
        degree: 'MCA',
        income: 1156252,
        currentCompany: 'Accenture',
        designation: 'Designer',
        maritalStatus: 'Never Married',
        languagesKnown: ['English', 'Tamil'],
        siblings: 1,
        caste: 'Agarwal',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '86',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Shreya',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '1993-08-27',
        age: 33,
        country: 'India',
        city: 'Jaipur',
        height: `6'5"`,
        email: 'shreya.mishra86@example.com',
        phoneNumber: '+91-9646875576',
        undergraduateCollege: 'IIM Indore',
        degree: 'M.Tech',
        income: 4370133,
        currentCompany: 'Microsoft',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 2,
        caste: 'Kayastha',
        religion: 'Sikh',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '87',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Manish',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1993-02-05',
        age: 33,
        country: 'India',
        city: 'Jaipur',
        height: `7'4"`,
        email: 'manish.mishra87@example.com',
        phoneNumber: '+91-8781527732',
        undergraduateCollege: 'VIT Vellore',
        degree: 'B.Tech ECE',
        income: 3231271,
        currentCompany: 'Tech Mahindra',
        designation: 'Consultant',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 0,
        caste: 'Yadav',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '88',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Kavya',
        lastName: 'Gupta',
        gender: 'Female',
        dateOfBirth: '2000-12-24',
        age: 26,
        country: 'India',
        city: 'Bangalore',
        height: `5'8"`,
        email: 'kavya.gupta88@example.com',
        phoneNumber: '+91-8307555530',
        undergraduateCollege: 'Delhi University',
        degree: 'B.Com',
        income: 4342267,
        currentCompany: 'Cognizant',
        designation: 'Senior Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 0,
        caste: 'Agarwal',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '89',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Amit',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '2001-08-18',
        age: 25,
        country: 'India',
        city: 'Ahmedabad',
        height: `6'1"`,
        email: 'amit.verma89@example.com',
        phoneNumber: '+91-7390011656',
        undergraduateCollege: 'NIT Trichy',
        degree: 'B.Tech ECE',
        income: 3999493,
        currentCompany: 'TCS',
        designation: 'Product Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 1,
        caste: 'Brahmin',
        religion: 'Jain',
        diet: 'Non-Vegetarian',
        wantKids: 'Maybe',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Matched',
      },
      {
        id: '90',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Neha',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '2002-10-20',
        age: 24,
        country: 'India',
        city: 'Kolkata',
        height: `5'4"`,
        email: 'neha.singh90@example.com',
        phoneNumber: '+91-9575468570',
        undergraduateCollege: 'NIFT',
        degree: 'B.Tech IT',
        income: 2705979,
        currentCompany: 'Google',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Marathi'],
        siblings: 2,
        caste: 'Kayastha',
        religion: 'Christian',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '91',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-happy-indian-260nw-2619939871.jpg',
        firstName: 'Ankit',
        lastName: 'Mishra',
        gender: 'Male',
        dateOfBirth: '1996-10-16',
        age: 30,
        country: 'India',
        city: 'Hyderabad',
        height: `6'7"`,
        email: 'ankit.mishra91@example.com',
        phoneNumber: '+91-8108386747',
        undergraduateCollege: 'BITS Pilani',
        degree: 'B.Com',
        income: 1496616,
        currentCompany: 'Wipro',
        designation: 'Developer',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Brahmin',
        religion: 'Jain',
        diet: 'Non-Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Reviewing',
      },
      {
        id: '92',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Sneha',
        lastName: 'Mishra',
        gender: 'Female',
        dateOfBirth: '2000-07-27',
        age: 26,
        country: 'India',
        city: 'Delhi',
        height: `5'7"`,
        email: 'sneha.mishra92@example.com',
        phoneNumber: '+91-9434287559',
        undergraduateCollege: 'Manipal University',
        degree: 'B.Des Fashion Design',
        income: 4969442,
        currentCompany: 'Tech Mahindra',
        designation: 'Developer',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English'],
        siblings: 3,
        caste: 'Kshatriya',
        religion: 'Hindu',
        diet: 'Eggetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Reviewing',
      },
      {
        id: '93',
        imageUrl:
          'https://www.shutterstock.com/image-photo/closeup-portrait-young-smiling-hispanic-260nw-2327799157.jpg',
        firstName: 'Ankit',
        lastName: 'Verma',
        gender: 'Male',
        dateOfBirth: '2002-06-03',
        age: 24,
        country: 'India',
        city: 'Bangalore',
        height: `7'0"`,
        email: 'ankit.verma93@example.com',
        phoneNumber: '+91-9225922508',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Tech IT',
        income: 619883,
        currentCompany: 'Infosys',
        designation: 'Consultant',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Punjabi'],
        siblings: 0,
        caste: 'Kshatriya',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'Yes',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '94',
        imageUrl:
          'https://thumb.photo-ac.com/87/87fec7029ae2a06a76b6e373cb4a7b57_t.jpeg',
        firstName: 'Pooja',
        lastName: 'Joshi',
        gender: 'Female',
        dateOfBirth: '1997-05-06',
        age: 29,
        country: 'India',
        city: 'Jaipur',
        height: `5'2"`,
        email: 'pooja.joshi94@example.com',
        phoneNumber: '+91-8624082473',
        undergraduateCollege: 'IIM Indore',
        degree: 'B.Des Fashion Design',
        income: 4215324,
        currentCompany: 'Microsoft',
        designation: 'Software Engineer',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 0,
        caste: 'Agarwal',
        religion: 'Jain',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'No',
        status: 'Searching',
      },
      {
        id: '95',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWAZLocXwjrQ1roL5oGFpxlt81NuoertoPmw&s',
        firstName: 'Rahul',
        lastName: 'Agarwal',
        gender: 'Male',
        dateOfBirth: '1997-09-03',
        age: 29,
        country: 'India',
        city: 'Pune',
        height: `6'1"`,
        email: 'rahul.agarwal95@example.com',
        phoneNumber: '+91-9882271946',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'B.Des Fashion Design',
        income: 1753834,
        currentCompany: 'Tech Mahindra',
        designation: 'Doctor',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Kshatriya',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'No',
        openToPets: 'No',
        status: 'Matched',
      },
      {
        id: '96',
        imageUrl:
          'https://images.pexels.com/photos/5341865/pexels-photo-5341865.jpeg?w=1260&h=750&dpr=1',
        firstName: 'Kavya',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '1998-09-26',
        age: 28,
        country: 'India',
        city: 'Chennai',
        height: `5'9"`,
        email: 'kavya.singh96@example.com',
        phoneNumber: '+91-7638710093',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Tech Computer Science',
        income: 1947538,
        currentCompany: 'Amazon',
        designation: 'Architect',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Maratha',
        religion: 'Christian',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '97',
        imageUrl:
          'https://www.shutterstock.com/image-photo/head-shot-portrait-millennial-30s-260nw-2555494759.jpg',
        firstName: 'Rohit',
        lastName: 'Singh',
        gender: 'Male',
        dateOfBirth: '1994-12-14',
        age: 32,
        country: 'India',
        city: 'Bangalore',
        height: `7'4"`,
        email: 'rohit.singh97@example.com',
        phoneNumber: '+91-8364773442',
        undergraduateCollege: 'IIT Bombay',
        degree: 'B.Com',
        income: 1387446,
        currentCompany: 'Accenture',
        designation: 'Architect',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Tamil'],
        siblings: 2,
        caste: 'Reddy',
        religion: 'Jain',
        diet: 'Eggetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Maybe',
        status: 'Searching',
      },
      {
        id: '98',
        imageUrl:
          'https://www.shutterstock.com/image-photo/profile-picture-smiling-millennial-indian-260nw-1997967170.jpg',
        firstName: 'Anjali',
        lastName: 'Joshi',
        gender: 'Female',
        dateOfBirth: '1991-07-07',
        age: 35,
        country: 'India',
        city: 'Chennai',
        height: `5'4"`,
        email: 'anjali.joshi98@example.com',
        phoneNumber: '+91-9101314321',
        undergraduateCollege: 'IIIT Hyderabad',
        degree: 'BBA',
        income: 697405,
        currentCompany: 'Accenture',
        designation: 'Doctor',
        maritalStatus: 'Divorced',
        languagesKnown: ['English', 'Telugu'],
        siblings: 0,
        caste: 'Kayastha',
        religion: 'Muslim',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Yes',
        openToPets: 'Yes',
        status: 'Searching',
      },
      {
        id: '99',
        imageUrl:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8XEA3eX8kstGdN2zxQI8MUgQhLV6ojM6sBA&s',
        firstName: 'Amit',
        lastName: 'Sharma',
        gender: 'Male',
        dateOfBirth: '1992-12-25',
        age: 34,
        country: 'India',
        city: 'Indore',
        height: `6'7"`,
        email: 'amit.sharma99@example.com',
        phoneNumber: '+91-9979430140',
        undergraduateCollege: 'IIT Delhi',
        degree: 'B.Tech ECE',
        income: 3351563,
        currentCompany: 'Google',
        designation: 'Manager',
        maritalStatus: 'Never Married',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 1,
        caste: 'Kshatriya',
        religion: 'Christian',
        diet: 'Vegetarian',
        wantKids: 'No',
        openToRelocate: 'Maybe',
        openToPets: 'Maybe',
        status: 'Matched',
      },
      {
        id: '100',
        imageUrl:
          'https://i.pinimg.com/564x/1b/43/84/1b4384eea372705219b56ab0c32dc6d6.jpg',
        firstName: 'Shreya',
        lastName: 'Singh',
        gender: 'Female',
        dateOfBirth: '2002-05-23',
        age: 24,
        country: 'India',
        city: 'Ahmedabad',
        height: `5'9"`,
        email: 'shreya.singh100@example.com',
        phoneNumber: '+91-7813172822',
        undergraduateCollege: 'VIT Vellore',
        degree: 'B.Tech Computer Science',
        income: 684387,
        currentCompany: 'HCL',
        designation: 'Product Manager',
        maritalStatus: 'Divorced',
        languagesKnown: ['Hindi', 'English', 'Gujarati'],
        siblings: 3,
        caste: 'Jain',
        religion: 'Muslim',
        diet: 'Eggetarian',
        wantKids: 'Maybe',
        openToRelocate: 'No',
        openToPets: 'Maybe',
        status: 'Searching',
      },
    ]

    // 4. INSERT THE NEW DATA
    console.log(`🌱 Inserting ${freshData.length} new profiles...`)
    await Profile.insertMany(freshData)
    console.log('✅ Database successfully seeded!')
  } catch (error) {
    console.error('❌ Error seeding database:', error)
  } finally {
    // 5. Close the connection so the script finishes cleanly
    await mongoose.connection.close()
    console.log('🔌 Database connection closed.')
    process.exit(0)
  }
}

seedDatabase()
