import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'

// Initialize Next.js optimized Google Fonts.
// Defining CSS variables here allows these fonts to be smoothly integrated into Tailwind classes across the app.
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Define global metadata for the application.
// Next.js uses this to automatically populate the HTML <head> tags (like <title>) for better SEO and browser tab naming.
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * RootLayout Component
 * This is the mandatory top-level wrapper for the entire Next.js App Router application.
 * Anything placed inside this component (styles, fonts, UI providers) will wrap every single page in your project.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // Apply the custom font variables and layout foundation directly to the root HTML document
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. Add Toaster here so it is available globally */}
        {/* Placing Toaster at the RootLayout level guarantees that toast popups can overlay over ANY page without needing to re-import it */}
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              borderRadius: '10px',
              background: '#333',
              color: '#fff',
            },
          }}
        />

        {/* The active page component (e.g., your Login or Dashboard page) is injected right here */}
        {children}
      </body>
    </html>
  )
}
